services:
    jitstreamer-eb:
        container_name: jitstreamer-eb
        network_mode: host #TODO, is bridge mode possible?
        volumes:
            - ./lockdown:/var/lib/lockdown
            - ./wireguard:/etc/wireguard
            - ./jitstreamer.db:/app/jitstreamer.db
        environment:
            - RUST_LOG=info
            - RUNNER_COUNT=1
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        image: jitstreamer-eb
        restart: unless-stopped

